Enhanced crosscompile build
- Create md5 sums of all archive files
- Fetch git tags and history to determine version number
- New artifact naming
- Added build timestamp in archive
- Status batches in README

diff --git a/.github/workflows/build_crosscompile.yml b/.github/workflows/build_crosscompile.yml
--- a/.github/workflows/build_crosscompile.yml
+++ b/.github/workflows/build_crosscompile.yml
@@ -1,5 +1,5 @@
 # GitHub Action to cross compile a YIO Remote Qt project for the YIO remote-os.
-# Uses the pre-build Buildroot SDK from remote-os.
+# Uses the pre-built Buildroot SDK from remote-os.
 #
 # TODO:
 # - Version tag / branch for integrations.library
@@ -22,13 +22,18 @@ env:
 
 jobs:
   cross_compile:
-    name: RPi Zero YIO remote-os
+    name: RPi0 YIO remote-os
     runs-on: ubuntu-latest
     steps:
       - name: Checkout integration plugin
         uses: actions/checkout@v2
         with:
+          fetch-depth: 0
           path: ${{ env.PROJECT_NAME}}
+      - name: Fetch all tags to determine version
+        run: |
+          cd ${{ env.PROJECT_NAME}}
+          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
       - name: Checkout integrations.library
         uses: actions/checkout@v2
         with:
@@ -41,6 +46,9 @@ jobs:
           mkdir -p /opt
           wget -qO- $BUILDROOT_SDK_BASE_URL/${BUILDROOT_SDK_VERSION}/${BUILDROOT_SDK_NAME}.tar.gz | tar -xz -C /opt
           /opt/${BUILDROOT_SDK_NAME}/relocate-sdk.sh
+
+      - name: Set build timestamp
+        run: echo "::set-env name=TIMESTAMP::$(date +"%Y%m%d_%H%M%S")"
 
       - name: Configure debug
         run: |
@@ -55,11 +63,14 @@ jobs:
       
       - name: Build debug
         run: |
+          # build plugin
           cd ${{ env.PROJECT_NAME}}/build
           PATH=${TOOLCHAIN_PATH}/bin:${TOOLCHAIN_PATH}/sbin:$PATH
           CPU_CORES=$(getconf _NPROCESSORS_ONLN)
           echo "Numbers of CPU cores for make: $CPU_CORES"
           make -j$CPU_CORES
+
+          # log build information
           echo "GitHub Actions debug build
           $(date)
           GIT branch: $(git rev-parse --abbrev-ref HEAD)
@@ -77,12 +88,34 @@ jobs:
           $(cpp --version)
           " > ${{ env.YIO_BIN }}/build.info
 
+      - name: Get plugin version
+        run: |
+          cd ${{ env.PROJECT_NAME}}/build
+          read -r PLUGIN_VERSION<version.txt
+          echo "Plugin version: $PLUGIN_VERSION"
+          echo "::set-env name=APP_VERSION::$PLUGIN_VERSION"
+
+      - name: Create debug installation
+        run: |
+          # copy additional files for the installation archive
+          cd ${{ env.PROJECT_NAME}}/build
+          cp homeassistant.json ${{ env.YIO_BIN }}
+          cp version.txt ${{ env.YIO_BIN }}
+          # hooks are optional: don't fail if missing
+          cp -r hooks ${{ env.YIO_BIN }} || :
+          # compress plugin
+          cd ${{ env.YIO_BIN }}
+          tar -czvf plugins.tar.gz plugins
+          rm -Rf plugins
+          # create checksums
+          md5sum * > md5sums
+
       - uses: actions/upload-artifact@v1
         id: upload_artifact_debug
         with:
           # Dear GitHub: dealing with env resolution is a PITA! ${{ env.YIO_BIN }} leads to a wrong path!!!
           path: ../binaries
-          name: ${{ env.APP_NAME}}-Qt${{ env.QT_VERSION }}-debug-ARM-RPi0
+          name: ${{ env.APP_NAME}}-${{ env.APP_VERSION}}-${{ env.TIMESTAMP}}-remote-debug
 
       - name: Configure release
         run: |
@@ -104,6 +137,8 @@ jobs:
           CPU_CORES=$(getconf _NPROCESSORS_ONLN)
           echo "Numbers of CPU cores for make: $CPU_CORES"
           make -j$CPU_CORES
+
+          # log build information
           echo "GitHub Actions release build
           $(date)
           GIT branch: $(git rev-parse --abbrev-ref HEAD)
@@ -121,9 +156,24 @@ jobs:
           $(cpp --version)
           " > ${{ env.YIO_BIN }}/build.info
 
+      - name: Create release installation
+        run: |
+          # copy additional files for the installation archive
+          cd ${{ env.PROJECT_NAME}}/build
+          cp homeassistant.json ${{ env.YIO_BIN }}
+          cp version.txt ${{ env.YIO_BIN }}
+          # hooks are optional: don't fail if missing
+          cp -r hooks ${{ env.YIO_BIN }} || :
+          # compress plugin
+          cd ${{ env.YIO_BIN }}
+          tar -czvf plugins.tar.gz plugins
+          rm -Rf plugins
+          # create checksums
+          md5sum * > md5sums
+
       - uses: actions/upload-artifact@v1
         id: upload_artifact_release
         with:
           # Dear GitHub: dealing with env resolution is a PITA! ${{ env.YIO_BIN }} leads to a wrong path!!!
           path: ../binaries
-          name: ${{ env.APP_NAME}}-Qt${{ env.QT_VERSION }}-release-ARM-RPi0
+          name: ${{ env.APP_NAME}}-${{ env.APP_VERSION}}-${{ env.TIMESTAMP}}-remote-release
